config/routes.rb
Rails.application.routes.draw do
  resources :customers, only: [:index, :show, :new, :create]
  resources :meal, only: [:index, :show, :new, :create]
  resource :customer_meals, only: [:index, :show, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :customer_meals
  has_many :meals, through: :customer_meals

  def money_spent
    @customer.meals.reduce(0) {| agg, meal| agg + meal.price}.round(2)
  end

  def calories_consumed
    self.meals.reduce(0) {| agg, meal| agg + meal.calories}
  end
end

app/models/customer_meal.rb
class CustomerMeal < ApplicationRecord
  belongs_to :customers
  belongs_to :meal
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :customer_meals
  has_many :customer, through: :customer_meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customer_meals_controller.rb
class CustomerMealsController < ApplicationController

  def new
    @customer_meal = CustomerMeal.create
  end

  def create
    @customer_meal = CustomerMeal.create(customer_meal_params)
    redirect_to customer_path(@customer_meal)
  end

  private

  def customer_meal_params
    params.require(:customer_meal).permit(:customer_id, :meal_id)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :find_customer, only: [:new]

  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)
    redirect_to customer_path(@customer)
  end

  private

  def find_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:name)
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def create
    @meal = Meal.create(meal_params)
    redirect_to meals_path
  end

  private

  def meal_params
    params.require(:meal).permit(:name, :price, :calories)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customer_meals/_form.erb
<div class="form">
<%= form_for @customermeal do |f| %>
  <%= cm.label :customer_id %>
  <%= cm.collection_select :customer_id, :id, @customers,:name %>
  <br/><br/>
  <%= cm.label :meals %>
  <%= cm.collection_select :meals, @meals, :id, :name %>

  <br/><br/>
  <%= cm.submit %>
<% end %>
</div>

app/views/customer_meals/new.erb
<h2 class="chili">Order Up!</h2>

<%= render "form" %>

app/views/customers/_form.erb
<%= form_for customer do |c| %>
  <%= c.label :name %>
  <%= c.text_field :name %>

  <%= c.submit %>
<% end %>

app/views/customers/index.erb
<h1 class="chili">List of Chili's Customers</h1>

<% @customers.each do |customer| %>
  <div class="customer"><%= link_to customer.name, customer%></div>
<% end %>

app/views/customers/new.erb
<h2>Create new customer</h2>

<%= render "form" %>

app/views/customers/show.erb
<h2 class="chili">Customer <%= @customer.name %></h2>

<h3 class="chili">Money Spent: $<%= customer.money_spent %></h3>
<h3 class="chili">Calories Consumed: <% @customers.calories_consumed %></h3>


<h3 class="chili center">All Orders</h3>

<div id="meals">
<% @customer.meals.each do |meal|%>
  <span class="customer-meal">
  <h4 class="pop"><%= @meal.name %></h4>
  <li class="pop">Calorie Count: <%= @meal.calories %></li>
  <li class="pop">$<% meal.price %></li>
  </span>
<% end %>
</div>

<p class="link"><% link_to "Make a new Order", new_customer_meal_path %></p>

<p class="link"><% link_to "All Customers", customer_path %></p>

<div><img src="https://images-na.ssl-images-amazon.com/images/I/31jLG5MvZ%2BL.jpg" alt="Hi" ></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrokenCode1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meals/_form.erb
<div class="form">
  <%= form_for: @meal do |m| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br/><br/>

    <%= f.label :price %>
    <%= m.number_field :price, step: 0.01 %>
    <br/><br/>

    <% m.label :calories %>
    <% m.number_field :calories %>
    <br/><br/>

    <%= m.submit %>
  <%= end %>
</div>

app/views/meals/index.erb
<h1 class="chili">Menu Items</h1>

<% @meals.all.each do |meal| %>
  <div class="meal"><%= link_to meal.name, @meal%></div>
<% end %>

<p class="link"><% link_to "Create Meal", new_meal_path %></p>

app/views/meals/new.erb
<h1 class="chili">Make a Custom Meal</h1>

<%= render "_form" %>